### ISSUE TITLE
Simplify Logic

### ISSUE THREAD

**Issue by madhavarshney** [srod/node-version#52]
Hi there!  I looked through the code and found that it can be a little simplified. The snippet below can be replaced by a simple [`process.versions.node`]( https://nodejs.org/api/process.html#process_process_versions):

https://github.com/srod/node-version/blob/4efd69fbe2bf97907a9216937fac82fe81947415/index.js#L8-L12

```js
var version = process.versions.node;
```

And this can be replaced with `long: version`:

https://github.com/srod/node-version/blob/4efd69fbe2bf97907a9216937fac82fe81947415/index.js#L19

If you don't mind, I can open a PR.

Thanks, Madhav.

**Comment by srod** [comment]
Hi,

Yes, PR welcome 👍 

Thank you !
